#!/bin/bash
echo "running custom build hook"

echo "JRE_VERSION=$BUILD_JRE_VERSION"
echo "WILDFLY_VERSION=$BUILD_WILDFLY_VERSION"
echo "S6_VERSION=$BUILD_S6_VERSION"
docker build \
    --build-arg JRE_VERSION="$BUILD_JRE_VERSION" \
    --build-arg WILDFLY_VERSION="$BUILD_WILDFLY_VERSION" \
    --build-arg S6_VERSION="$BUILD_S6_VERSION" \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
